### ISSUE TITLE
Error in type variable instantiation

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#11]
Reproducible code:

```
i = 1 + 1
```

Error log:

```console
compiler\erg_compiler\compile.rs:160: [DEBUG] the compiling process has started.
compiler\erg_parser\parse.rs:325: [DEBUG] the parsing process has started.
compiler\erg_parser\parse.rs:326: token stream: [Symbol i, Equal =, NatLit 1, Plus +, NatLit 1, EOF ]
compiler\erg_parser\parse.rs:358: [DEBUG] entered try_reduce_module, cur: Symbol i
compiler\erg_parser\parse.rs:1252: [DEBUG] entered try_reduce_expr, cur: Symbol i
compiler\erg_parser\parse.rs:472: [DEBUG] entered try_reduce_decl, cur: Symbol i
compiler\erg_parser\parse.rs:1482: [DEBUG] entered try_reduce_name, cur: Symbol i
compiler\erg_parser\parse.rs:686: [DEBUG] entered opt_reduce_params, cur: Equal =
compiler\erg_parser\parse.rs:386: [DEBUG] entered try_reduce_block, cur: NatLit 1
compiler\erg_parser\parse.rs:1252: [DEBUG] entered try_reduce_expr, cur: NatLit 1
compiler\erg_parser\parse.rs:1395: [DEBUG] entered try_reduce_lhs, cur: NatLit 1
compiler\erg_parser\parse.rs:1491: [DEBUG] entered try_reduce_lit, cur: NatLit 1
compiler\erg_parser\parse.rs:1395: [DEBUG] entered try_reduce_lhs, cur: NatLit 1
compiler\erg_parser\parse.rs:1491: [DEBUG] entered try_reduce_lit, cur: NatLit 1
compiler\erg_parser\parse.rs:340: [DEBUG] the parsing process has completed.
compiler\erg_parser\parse.rs:341: AST:
i =
    `+`:
        NatLit 1
        NatLit 1
compiler\erg_parser\parse.rs:342: [DEBUG] the desugaring process has started.
compiler\erg_parser\parse.rs:345: AST (desugared):
i =
    `+`:
        NatLit 1
        NatLit 1
compiler\erg_parser\parse.rs:346: [DEBUG] the desugaring process has completed.
compiler\erg_compiler\lower.rs:386: [DEBUG] the type-checking process has started.
compiler\erg_compiler\lower.rs:361: [DEBUG] entered lower_expr
compiler\erg_compiler\lower.rs:254: [DEBUG] entered lower_def(i)
compiler\erg_compiler\context.rs:3493: grow: current namespace: <module>::i
compiler\erg_compiler\lower.rs:272: [DEBUG] entered lower_var_def(i)
compiler\erg_compiler\lower.rs:376: [DEBUG] entered lower_block
compiler\erg_compiler\lower.rs:361: [DEBUG] entered lower_expr
compiler\erg_compiler\lower.rs:142: [DEBUG] entered lower_bin(`+`:
    NatLit 1
    NatLit 1)
compiler\erg_compiler\lower.rs:361: [DEBUG] entered lower_expr
compiler\erg_compiler\lower.rs:361: [DEBUG] entered lower_expr
compiler\erg_compiler\context.rs:2660: Found:
callee: __add__
found: |{'L <: Add('R, 'O), 'O: Type, 'R: Type}| ('L, 'R) -> 'O
thread 'main' panicked at 'not yet implemented', compiler\erg_compiler\context.rs:260:21
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:48
   3: erg_compiler::context::TyVarContext::instantiate_tp
             at .\compiler\erg_compiler\context.rs:260

...

  28: erg::main
             at .\src\main.rs:31
  29: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
ConnectionAbortedError: [WinError 10053] 確立された接続がホスト コンピューターのソウトウェアによって中止されました。
error: process didn't exit successfully: `target\debug\erg.exe` (exit code: 101)
```

I have already pinpointed the cause.
It is due to the fact that during TyVarContext::new, there is an order dependency in the initialization of the type variable, yet it is ignored.

```rust
    pub fn new(level: usize, bounds: Set<TyBound>) -> Self {
        let mut self_ = Self {
            level,
            tyvar_instances: Dict::new(),
            typaram_instances: Dict::new(),
        };
        for bound in bounds.into_iter() { # this is wrong, the order should be sorted
            self_.instantiate_bound(bound);
        }
        } self_.
    }
```

We need to sort the type variables according to the order of dependencies.
Fortunately, I had a function in erg_common that does topological sorting, so this would be a quick fix.

**Comment by mtshiba** [comment]
This was fixed in Erg 0.2.3.
