### ISSUE TITLE
Crash with importing on REPL

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#176]
**Reproducible code**
```
>>> a11y = import "examples/a11y"
```

**Expected behavior**

Passed.

**Result**

```console
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 10054, kind: ConnectionReset, message: "既存の接続はリモート ホストに強制的に切断されました。" }', src\dummy.rs:77:49
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\result.rs:1805
   3: enum$<core::result::Result<tuple$<>,std::io::error::Error>, 1, 18446744073709551615, Err>::unwrap<tuple$<>,std::io::error::Error>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\result.rs:1098
   4: erg::dummy::impl$0::finish
             at .\src\dummy.rs:77
   5: erg::dummy::impl$0::eval
             at .\src\dummy.rs:120
   6: erg_common::traits::Runnable::run<erg::dummy::DummyVM>
             at .\compiler\erg_common\traits.rs:443
   7: erg::run
             at .\src\main.rs:41
   8: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src\main.rs:63:22
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\result.rs:1805
   3: enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> >, 1, 18446744073709551615, Err>::unwrap<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\result.rs:1098
   4: erg::main
             at .\src\main.rs:63
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Additional Context**

This will be passed. It's strange.

```
>>> None

>>> a11y = import "examples/a11y"
```

**Comment by GreasySlug** [comment]
This may also possibly be a problem on the windows side.

https://github.com/erg-lang/erg/blob/3210fcbf00f9700128ff48a2a4c4d6cdd6297cfb/src/dummy.rs#L108-L112

If I set the size of the buffer to be allocated to 2048, it works.

```sh
>>> a11y = import "examples/a11y" 
None
>>> fib = import "examples/fib"
55  
None
```
