### ISSUE TITLE
Operator error messages are not displayed and cause panic

### ISSUE THREAD

**Issue by GreasySlug** [erg-lang/erg#19]
OS: Windows
python-version: 3.10.6

##  Reproduction Steps 

1. In REPl or scripts, write code that intentionally causes errors by using operators.

```
# only operator:*, -
+ 
```

2. Panic instead of error messages.

```sh
> erg
Starting the REPL server...
Connecting to the REPL server...
Erg interpreter 0.2.2 (tags/?:6d3dda8, 2022/08/15  5:30:08.61) on x86_64/windows
>>> +
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', compiler\erg_parser\lex.rs:682:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<string>", line 17, in <module>
ConnectionAbortedError: [WinError 10053] 確立された接続がホスト コンピューターのソウトウェアによって中止されました。
```

I expected like REPL of python

```sh
> python
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> +
  File "<stdin>", line 1
    +
     ^
SyntaxError: invalid syntax
```

**Comment by GreasySlug** [comment]
I don't know well, but this issue has already fixed.
