### ISSUE TITLE
`if True, ...` doesn't work

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#98]
**Reproducible code**
```
>>> if True, do:
...   log 1
```

**Expected behavior**
prints `1`.

**Result**
```
...
Traceback (most recent call last):
  File "<string>", line 28, in <module>
  File "<string>", line 1, in <module>
  File "<stdin>", line -1, in <module>
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 32, in <module>
NameError: name 'e' is not defined

>>>
```

**Comment by mtshiba** [comment]
This code is compiled as follows:

```
1:
              0 LOAD_NAME                0 (print)
              2 LOAD_CONST               0 (True)
              4 POP_JUMP_IF_FALSE        6 (to 12)
2:
              6 LOAD_NAME                1 (print)
              8 LOAD_CONST               1 (1)
             10 CALL_FUNCTION            1
             12 LOAD_CONST               2 (None)
             14 CALL_FUNCTION            1
             16 LOAD_CONST               2 (None)
             18 RETURN_VALUE

```

`None` (in position 12) is the value returned when `cond` is `False`, but because it is put on the stack, 1 is being called when `print!` should be called.

**Comment by GreasySlug** [comment]
I think this has been resolved.

```shell
>>> if! True, do!:
...     print! 1   
... 
1
>>> if True, do:
...     log 1
... 
1
```

**Comment by mtshiba** [comment]
Now the `False` case does not work.

```erg
if False, do:
  log 1
```
